json.id story.id
json.title story.title
json.description story.description
json.story_type story.story_type
json.iteration story.iteration
json.complexity story.complexity
json.status story.status
json.project_id story.project_id
json.priority story.priority