json.id story.id
json.description story.description
json.story_type story.story_type
json.iteration story.iteration
json.complexity story.complexity
json.project_id story.project_id
json.priority story.priority
json.assigned_to story.assigned_to
json.created_at story.created_at